[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
    'npm ci',
    'cd apps/web && npm ci'
]

[phases.build] 
cmds = [
    'cd apps/web && npm run build'
]

[start]
cmd = 'cd apps/web && npm start'